modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dd_mod"
version="1.0.0"
displayName="d&d mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Millers, MCreator"

[[dependencies.dd_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




